name: ✨ Feature request
description: Suggest an improvement to the showcase site itself.
title: "Feature: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's the motivation?
      description: What's missing or could be better?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
